site_name: CodeSee Beta
nav:
  - ğŸ‘‹ Introduction: index.md
  - ğŸ›  Installing CodeSee:
    - Installation and setup: installation.md
    - Create React App: setup-cra.md
    - Typescript without Babel: setup-typescript-without-babel.md
    - Next: setup-next.md
    - Nuxt: setup-nuxt.md
    - Storybook: setup-storybook.md
    - Gatsby: setup-gatsby.md
    - Ember: setup-ember.md
    - Generic setup: setup-generic.md
    - Configuration options: options.md
  - ğŸš€ Using CodeSee:
    - Quick start guide: quick-start.md
    - Ways to use CodeSee: use-cases.md
  - âš™ï¸ Advanced setup:
    - Updating pre-0.7.0 to the latest: upgrade-local-version.md
    - Running CodeSee locally: local.md
    - Running CodeSee on the Backend: backend.md
    - Changing from local to hosted CodeSee: hosted.md
  - ğŸ™ Troubleshooting: troubleshooting.md
theme:
  name: material
  favicon: img/favicon-32x32.png
  font: false
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codeseeio
copyright: Copyright &copy; 2021 CodeSee Inc

